export const cities = [
    {
        id: "1",
        name: "Ikeja",
        longitude: 3.3500,
        latitude: 6.6018,
        address: "Ikeja, Lagos",
        backgroundImage: "https://example.com/ikeja.jpg",
        subtitle: "Capital District • Government & Business Hub",
        dailyActive: 5200,
        inventory: "High",
        screens: 12,
    },
    {
        id: "2",
        name: "Surulere",
        longitude: 3.3580,
        latitude: 6.4969,
        address: "Surulere, Lagos",
        backgroundImage: "https://example.com/surulere.jpg",
        subtitle: "Central Lagos • Stadium & Residential Powerhouse",
        dailyActive: 4100,
        inventory: "Medium",
        screens: 9,
    },
    {
        id: "3",
        name: "Yaba",
        longitude: 3.3676,
        latitude: 6.5158,
        address: "Yaba, Lagos",
        backgroundImage: "https://example.com/yaba.jpg",
        subtitle: "Tech Hub • Universities & Startups",
        dailyActive: 4800,
        inventory: "High",
        screens: 11,
    },
    {
        id: "4",
        name: "Victoria Island",
        longitude: 3.4219,
        latitude: 6.4281,
        address: "Victoria Island, Lagos",
        backgroundImage: "https://example.com/vi.jpg",
        subtitle: "Corporate Lagos • Finance, Offices & Nightlife",
        dailyActive: 6000,
        inventory: "High",
        screens: 14,
    },
    {
        id: "5",
        name: "Lekki",
        longitude: 3.6000,
        latitude: 6.4500,
        address: "Lekki, Lagos",
        backgroundImage: "https://example.com/lekki.jpg",
        subtitle: "Fast-Growing District • Estates, Malls & New Money",
        dailyActive: 5300,
        inventory: "High",
        screens: 13,
    },
    {
        id: "6",
        name: "Ikorodu",
        longitude: 3.5095,
        latitude: 6.6194,
        address: "Ikorodu, Lagos",
        backgroundImage: "https://example.com/ikorodu.jpg",
        subtitle: "High Population Zone • Mainland Mega District",
        dailyActive: 4500,
        inventory: "Medium",
        screens: 10,
    },
    {
        id: "7",
        name: "Ajah",
        longitude: 3.5400,
        latitude: 6.4700,
        address: "Ajah, Lagos",
        backgroundImage: "https://example.com/ajah.jpg",
        subtitle: "Lekki Corridor • Busy Junction & Housing Expansion",
        dailyActive: 3900,
        inventory: "Medium",
        screens: 8,
    },
    {
        id: "8",
        name: "Apapa",
        longitude: 3.3603,
        latitude: 6.4483,
        address: "Apapa, Lagos",
        backgroundImage: "https://example.com/apapa.jpg",
        subtitle: "Ports & Logistics • Heavy Commercial Movement",
        dailyActive: 3600,
        inventory: "High",
        screens: 7,
    },
    {
        id: "9",
        name: "Badagry",
        longitude: 2.8876,
        latitude: 6.4176,
        address: "Badagry, Lagos",
        backgroundImage: "https://example.com/badagry.jpg",
        subtitle: "Border Town • Tourism, Trade & Heritage",
        dailyActive: 2200,
        inventory: "Low",
        screens: 5,
    },
    {
        id: "10",
        name: "Epe",
        longitude: 3.9830,
        latitude: 6.5860,
        address: "Epe, Lagos",
        backgroundImage: "https://example.com/epe.jpg",
        subtitle: "Lagos Expansion Zone • Agriculture & New Developments",
        dailyActive: 1800,
        inventory: "Low",
        screens: 4,
    },
    {
        id: "11",
        name: "Oshodi",
        longitude: 3.3436,
        latitude: 6.5536,
        address: "Oshodi, Lagos",
        backgroundImage: "https://example.com/oshodi.jpg",
        subtitle: "Transport Core • One of Lagos’ Busiest Hubs",
        dailyActive: 6500,
        inventory: "High",
        screens: 15,
    },
    {
        id: "12",
        name: "Agege",
        longitude: 3.3200,
        latitude: 6.6150,
        address: "Agege, Lagos",
        backgroundImage: "https://example.com/agege.jpg",
        subtitle: "Dense Mainland • Markets, Transit & Residential",
        dailyActive: 4300,
        inventory: "Medium",
        screens: 9,
    },
    {
        id: "AKS_1",
        name: "Uyo",
        longitude: 7.9266,
        latitude: 5.0389,
        address: "Uyo, Akwa Ibom",
        backgroundImage: "https://example.com/uyo.jpg",
        subtitle: "Capital City & Business Center",
        ExtPopulation: 554000,
        density: "High",
        possible_points: 25,
    },

    {
        id: "AKS_2",
        name: "Ikot Ekpene",
        longitude: 7.7146,
        latitude: 5.1819,
        address: "Ikot Ekpene, Akwa Ibom",
        backgroundImage: "https://example.com/ikot-ekpene.jpg",
        subtitle: "Commercial Hub & Craft Center",
        ExtPopulation: 250000,
        density: "Medium",
        possible_points: 16,
    },

    {
        id: "AKS_3",
        name: "Eket",
        longitude: 7.9337,
        latitude: 4.6423,
        address: "Eket, Akwa Ibom",
        backgroundImage: "https://example.com/eket.jpg",
        subtitle: "Oil & Gas Town",
        ExtPopulation: 180000,
        density: "Medium",
        possible_points: 14,
    },

    {
        id: "AKS_4",
        name: "Oron",
        longitude: 8.2337,
        latitude: 4.8217,
        address: "Oron, Akwa Ibom",
        backgroundImage: "https://example.com/oron.jpg",
        subtitle: "Coastal Town & Maritime Trade",
        ExtPopulation: 150000,
        density: "Medium",
        possible_points: 13,
    },

    {
        id: "AKS_5",
        name: "Abak",
        longitude: 7.7890,
        latitude: 4.9827,
        address: "Abak, Akwa Ibom",
        backgroundImage: "https://example.com/abak.jpg",
        subtitle: "Busy Inland Market Town",
        ExtPopulation: 120000,
        density: "Medium",
        possible_points: 10,
    },

    {
        id: "AKS_6",
        name: "Etinan",
        longitude: 7.8506,
        latitude: 4.8426,
        address: "Etinan, Akwa Ibom",
        backgroundImage: "https://example.com/etinan.jpg",
        subtitle: "Market Town & Transport Link",
        ExtPopulation: 100000,
        density: "Medium",
        possible_points: 9,
    },

    {
        id: "AKS_7",
        name: "Itu",
        longitude: 7.9826,
        latitude: 5.2013,
        address: "Itu, Akwa Ibom",
        backgroundImage: "https://example.com/itu.jpg",
        subtitle: "Gateway Town (Cross River Axis)",
        ExtPopulation: 95000,
        density: "Medium",
        possible_points: 9,
    },

    {
        id: "AKS_8",
        name: "Ikot Abasi",
        longitude: 7.5464,
        latitude: 4.5716,
        address: "Ikot Abasi, Akwa Ibom",
        backgroundImage: "https://example.com/ikot-abasi.jpg",
        subtitle: "Industrial & Coastal Economy",
        ExtPopulation: 90000,
        density: "Medium",
        possible_points: 8,
    },

    {
        id: "AKS_9",
        name: "Mkpat Enin",
        longitude: 7.7383,
        latitude: 4.7348,
        address: "Mkpat Enin, Akwa Ibom",
        backgroundImage: "https://example.com/mkpat-enin.jpg",
        subtitle: "Growing Town Near Eket Axis",
        ExtPopulation: 80000,
        density: "Medium",
        possible_points: 7,
    },

    {
        id: "AKS_10",
        name: "Ibeno",
        longitude: 7.9800,
        latitude: 4.5560,
        address: "Ibeno, Akwa Ibom",
        backgroundImage: "https://example.com/ibeno.jpg",
        subtitle: "Beach Town & Oil-Producing Area",
        ExtPopulation: 70000,
        density: "Low",
        possible_points: 8,
    },

    {
        id: "AKS_11",
        name: "Ukanafun",
        longitude: 7.6190,
        latitude: 4.9140,
        address: "Ukanafun, Akwa Ibom",
        backgroundImage: "https://example.com/ukanafun.jpg",
        subtitle: "Busy Rural Town & Market Area",
        ExtPopulation: 65000,
        density: "Low",
        possible_points: 6,
    },

    {
        id: "AKS_12",
        name: "Ibiono Ibom",
        longitude: 7.9790,
        latitude: 5.2080,
        address: "Ibiono Ibom, Akwa Ibom",
        backgroundImage: "https://example.com/ibiono-ibom.jpg",
        subtitle: "Large LGA with Many Villages",
        ExtPopulation: 60000,
        density: "Low",
        possible_points: 6,
    },
    {
        id: "ANB_1",
        name: "Awka",
        longitude: 7.0684,
        latitude: 6.2104,
        address: "Awka, Anambra",
        backgroundImage: "https://example.com/awka.jpg",
        subtitle: "State Capital & Administrative Center",
        ExtPopulation: 350000,
        density: "High",
        possible_points: 18,
    },

    {
        id: "ANB_2",
        name: "Onitsha",
        longitude: 6.7884,
        latitude: 6.1498,
        address: "Onitsha, Anambra",
        backgroundImage: "https://example.com/onitsha.jpg",
        subtitle: "Mega Market City & Commercial Hub",
        ExtPopulation: 1200000,
        density: "Very High",
        possible_points: 28,
    },

    {
        id: "ANB_3",
        name: "Nnewi",
        longitude: 6.9141,
        latitude: 6.0196,
        address: "Nnewi, Anambra",
        backgroundImage: "https://example.com/nnewi.jpg",
        subtitle: "Industrial City & Auto Parts Capital",
        ExtPopulation: 600000,
        density: "High",
        possible_points: 22,
    },

    {
        id: "ANB_4",
        name: "Ekwulobia",
        longitude: 7.0106,
        latitude: 5.9944,
        address: "Ekwulobia, Anambra",
        backgroundImage: "https://example.com/ekwulobia.jpg",
        subtitle: "Major Town in Aguata Axis",
        ExtPopulation: 180000,
        density: "Medium",
        possible_points: 14,
    },

    {
        id: "ANB_5",
        name: "Nkpor",
        longitude: 6.7920,
        latitude: 6.1510,
        address: "Nkpor, Anambra",
        backgroundImage: "https://example.com/nkpor.jpg",
        subtitle: "Onitsha Suburb & Trading Town",
        ExtPopulation: 250000,
        density: "High",
        possible_points: 15,
    },

    {
        id: "ANB_6",
        name: "Obosi",
        longitude: 6.8083,
        latitude: 6.1470,
        address: "Obosi, Anambra",
        backgroundImage: "https://example.com/obosi.jpg",
        subtitle: "Dense Urban Town Near Onitsha",
        ExtPopulation: 220000,
        density: "High",
        possible_points: 13,
    },

    {
        id: "ANB_7",
        name: "Ogidi",
        longitude: 6.8620,
        latitude: 6.1620,
        address: "Ogidi, Anambra",
        backgroundImage: "https://example.com/ogidi.jpg",
        subtitle: "Historic Town & Growing Urban Area",
        ExtPopulation: 160000,
        density: "Medium",
        possible_points: 11,
    },

    {
        id: "ANB_8",
        name: "Ihiala",
        longitude: 6.8592,
        latitude: 5.8541,
        address: "Ihiala, Anambra",
        backgroundImage: "https://example.com/ihiala.jpg",
        subtitle: "Border Town & Major Transport Link",
        ExtPopulation: 140000,
        density: "Medium",
        possible_points: 12,
    },

    {
        id: "ANB_9",
        name: "Ozubulu",
        longitude: 6.8780,
        latitude: 5.9510,
        address: "Ozubulu, Anambra",
        backgroundImage: "https://example.com/ozubulu.jpg",
        subtitle: "Busy Town Along the Nnewi Axis",
        ExtPopulation: 110000,
        density: "Medium",
        possible_points: 10,
    },

    {
        id: "ANB_10",
        name: "Umunze",
        longitude: 7.2300,
        latitude: 5.9660,
        address: "Umunze, Anambra",
        backgroundImage: "https://example.com/umunze.jpg",
        subtitle: "Education Town & Southern Anambra Hub",
        ExtPopulation: 90000,
        density: "Low",
        possible_points: 8,
    },

    {
        id: "ANB_11",
        name: "Aguleri",
        longitude: 6.9500,
        latitude: 6.3160,
        address: "Aguleri, Anambra",
        backgroundImage: "https://example.com/aguleri.jpg",
        subtitle: "River Town & Cultural Center",
        ExtPopulation: 80000,
        density: "Low",
        possible_points: 8,
    },

    {
        id: "ANB_12",
        name: "Otuocha",
        longitude: 6.8500,
        latitude: 6.3300,
        address: "Otuocha, Anambra",
        backgroundImage: "https://example.com/otuoch.jpg",
        subtitle: "Trading Town (Anambra East Axis)",
        ExtPopulation: 75000,
        density: "Low",
        possible_points: 7,
    },
    {
        id: "ENU_1",
        name: "Enugu",
        longitude: 7.5100,
        latitude: 6.4500,
        address: "Enugu, Enugu",
        backgroundImage: "https://example.com/enugu.jpg",
        subtitle: "Coal City & State Capital",
        ExtPopulation: 900000,
        density: "High",
        possible_points: 26,
    },

    {
        id: "ENU_2",
        name: "Nsukka",
        longitude: 7.3986,
        latitude: 6.8578,
        address: "Nsukka, Enugu",
        backgroundImage: "https://example.com/nsukka.jpg",
        subtitle: "University Town & Northern Enugu Hub",
        ExtPopulation: 300000,
        density: "Medium",
        possible_points: 18,
    },

    {
        id: "ENU_3",
        name: "Agbani",
        longitude: 7.5480,
        latitude: 6.3060,
        address: "Agbani, Enugu",
        backgroundImage: "https://example.com/agbani.jpg",
        subtitle: "Administrative Town (Nkanu West HQ)",
        ExtPopulation: 90000,
        density: "Low",
        possible_points: 9,
    },

    {
        id: "ENU_4",
        name: "Awgu",
        longitude: 7.4800,
        latitude: 6.0700,
        address: "Awgu, Enugu",
        backgroundImage: "https://example.com/awgu.jpg",
        subtitle: "Southern Enugu Town & LGA HQ",
        ExtPopulation: 85000,
        density: "Low",
        possible_points: 8,
    },

    {
        id: "ENU_5",
        name: "Oji River",
        longitude: 7.2700,
        latitude: 6.2500,
        address: "Oji River, Enugu",
        backgroundImage: "https://example.com/oji-river.jpg",
        subtitle: "Transit Town & Power Station Area",
        ExtPopulation: 120000,
        density: "Medium",
        possible_points: 11,
    },

    {
        id: "ENU_6",
        name: "Udi",
        longitude: 7.4200,
        latitude: 6.3200,
        address: "Udi, Enugu",
        backgroundImage: "https://example.com/udi.jpg",
        subtitle: "Hill Town & Major Local Center",
        ExtPopulation: 100000,
        density: "Medium",
        possible_points: 10,
    },

    {
        id: "ENU_7",
        name: "Ngwo",
        longitude: 7.4700,
        latitude: 6.4600,
        address: "Ngwo, Enugu",
        backgroundImage: "https://example.com/ngwo.jpg",
        subtitle: "Enugu Suburb & Waterfall Area",
        ExtPopulation: 150000,
        density: "Medium",
        possible_points: 12,
    },

    {
        id: "ENU_8",
        name: "Obollo-Afor",
        longitude: 7.4700,
        latitude: 6.9200,
        address: "Obollo-Afor, Enugu",
        backgroundImage: "https://example.com/obollo-afor.jpg",
        subtitle: "Major Market Town (Udenu Axis)",
        ExtPopulation: 90000,
        density: "Low",
        possible_points: 9,
    },

    {
        id: "ENU_9",
        name: "Ibagwa Aka",
        longitude: 7.4100,
        latitude: 6.8600,
        address: "Ibagwa Aka, Enugu",
        backgroundImage: "https://example.com/ibagwa-aka.jpg",
        subtitle: "Large Town (Igbo Eze South HQ)",
        ExtPopulation: 75000,
        density: "Low",
        possible_points: 7,
    },

    {
        id: "ENU_10",
        name: "Aguobu-Owa",
        longitude: 7.2600,
        latitude: 6.2800,
        address: "Aguobu-Owa, Enugu",
        backgroundImage: "https://example.com/aguobu-owa.jpg",
        subtitle: "Ezeagu LGA HQ & Market Center",
        ExtPopulation: 70000,
        density: "Low",
        possible_points: 7,
    },

    {
        id: "ENU_11",
        name: "Ikem",
        longitude: 7.6900,
        latitude: 6.1400,
        address: "Ikem, Enugu",
        backgroundImage: "https://example.com/ikem.jpg",
        subtitle: "Isi-Uzo Axis & Agricultural Town",
        ExtPopulation: 65000,
        density: "Low",
        possible_points: 6,
    },

    {
        id: "ENU_12",
        name: "Amagunze",
        longitude: 7.6200,
        latitude: 6.2400,
        address: "Amagunze, Enugu",
        backgroundImage: "https://example.com/amagunze.jpg",
        subtitle: "Nkanu East Axis & Growing Town",
        ExtPopulation: 60000,
        density: "Low",
        possible_points: 6,
    }, {
        id: "FCT_1",
        name: "Central Area",
        longitude: 7.4913,
        latitude: 9.0579,
        address: "Central Area, Abuja (FCT)",
        backgroundImage: "https://example.com/central-area.jpg",
        subtitle: "CBD & Government District",
        ExtPopulation: 250000,
        density: "High",
        possible_points: 20,
    },

    {
        id: "FCT_2",
        name: "Garki",
        longitude: 7.4890,
        latitude: 9.0320,
        address: "Garki, Abuja (FCT)",
        backgroundImage: "https://example.com/garki.jpg",
        subtitle: "Busy Commercial District",
        ExtPopulation: 500000,
        density: "Very High",
        possible_points: 22,
    },

    {
        id: "FCT_3",
        name: "Wuse",
        longitude: 7.4750,
        latitude: 9.0800,
        address: "Wuse, Abuja (FCT)",
        backgroundImage: "https://example.com/wuse.jpg",
        subtitle: "Shopping & Business District",
        ExtPopulation: 450000,
        density: "Very High",
        possible_points: 21,
    },

    {
        id: "FCT_4",
        name: "Maitama",
        longitude: 7.5000,
        latitude: 9.0900,
        address: "Maitama, Abuja (FCT)",
        backgroundImage: "https://example.com/maitama.jpg",
        subtitle: "Diplomatic & High-End Area",
        ExtPopulation: 200000,
        density: "Medium",
        possible_points: 18,
    },

    {
        id: "FCT_5",
        name: "Asokoro",
        longitude: 7.5200,
        latitude: 9.0200,
        address: "Asokoro, Abuja (FCT)",
        backgroundImage: "https://example.com/asokoro.jpg",
        subtitle: "Presidential & Elite Residential District",
        ExtPopulation: 180000,
        density: "Medium",
        possible_points: 17,
    },

    {
        id: "FCT_6",
        name: "Gwarinpa",
        longitude: 7.3900,
        latitude: 9.1100,
        address: "Gwarinpa, Abuja (FCT)",
        backgroundImage: "https://example.com/gwarinpa.jpg",
        subtitle: "Largest Residential Estate Area",
        ExtPopulation: 600000,
        density: "High",
        possible_points: 19,
    },

    {
        id: "FCT_7",
        name: "Jabi",
        longitude: 7.4200,
        latitude: 9.0800,
        address: "Jabi, Abuja (FCT)",
        backgroundImage: "https://example.com/jabi.jpg",
        subtitle: "Lake Area & Modern Leisure District",
        ExtPopulation: 220000,
        density: "High",
        possible_points: 16,
    },

    {
        id: "FCT_8",
        name: "Utako",
        longitude: 7.4400,
        latitude: 9.0700,
        address: "Utako, Abuja (FCT)",
        backgroundImage: "https://example.com/utako.jpg",
        subtitle: "Transport & Business Hub",
        ExtPopulation: 200000,
        density: "High",
        possible_points: 14,
    },

    {
        id: "FCT_9",
        name: "Kubwa",
        longitude: 7.3300,
        latitude: 9.1600,
        address: "Kubwa, Abuja (FCT)",
        backgroundImage: "https://example.com/kubwa.jpg",
        subtitle: "Largest Satellite Town",
        ExtPopulation: 800000,
        density: "Very High",
        possible_points: 23,
    },

    {
        id: "FCT_10",
        name: "Lugbe",
        longitude: 7.3800,
        latitude: 8.9800,
        address: "Lugbe, Abuja (FCT)",
        backgroundImage: "https://example.com/lugbe.jpg",
        subtitle: "Fast-Growing Airport Road District",
        ExtPopulation: 500000,
        density: "High",
        possible_points: 18,
    },

    {
        id: "FCT_11",
        name: "Nyanya",
        longitude: 7.5700,
        latitude: 9.0000,
        address: "Nyanya, Abuja (FCT)",
        backgroundImage: "https://example.com/nyanya.jpg",
        subtitle: "Major Entry Point & Dense Residential Area",
        ExtPopulation: 700000,
        density: "Very High",
        possible_points: 20,
    },

    {
        id: "FCT_12",
        name: "Gwagwalada",
        longitude: 7.0700,
        latitude: 8.9500,
        address: "Gwagwalada, Abuja (FCT)",
        backgroundImage: "https://example.com/gwagwalada.jpg",
        subtitle: "University Town & FCT Area Council HQ",
        ExtPopulation: 250000,
        density: "Medium",
        possible_points: 14,
    },

    {
        id: "FCT_13",
        name: "Kuje",
        longitude: 7.2300,
        latitude: 8.8800,
        address: "Kuje, Abuja (FCT)",
        backgroundImage: "https://example.com/kuje.jpg",
        subtitle: "Satellite Town & Area Council HQ",
        ExtPopulation: 180000,
        density: "Medium",
        possible_points: 12,
    },

    {
        id: "FCT_14",
        name: "Bwari",
        longitude: 7.3400,
        latitude: 9.2800,
        address: "Bwari, Abuja (FCT)",
        backgroundImage: "https://example.com/bwari.jpg",
        subtitle: "Northern Abuja Town & Education Axis",
        ExtPopulation: 160000,
        density: "Medium",
        possible_points: 11,
    },

    {
        id: "FCT_15",
        name: "Abaji",
        longitude: 6.9500,
        latitude: 8.4700,
        address: "Abaji, Abuja (FCT)",
        backgroundImage: "https://example.com/abaji.jpg",
        subtitle: "Western FCT Town & Area Council HQ",
        ExtPopulation: 90000,
        density: "Low",
        possible_points: 8,
    }
];